# Generated by Django 5.0.6 on 2024-06-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='buyed_boats',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='buyed_guns',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='buyed_places',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='buyed_rods',
        ),
    ]
