# Generated by Django 5.0.6 on 2024-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_baseuser_buyed_boats_and_more'),
        ('products', '0003_remove_fisingrod_category_remove_gun_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='buyed_products',
            field=models.ManyToManyField(related_name='users_buy', to='products.product'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='cart',
            field=models.ManyToManyField(related_name='users_carted', to='products.product'),
        ),
    ]
