# Generated by Django 5.0.6 on 2024-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_weaponapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentplace',
            name='grade',
        ),
        migrations.AlterField(
            model_name='rentplace',
            name='location',
            field=models.CharField(choices=[('ru', 'Россия'), ('br', 'Бразилия'), ('it', 'Италия'), ('kn', 'Кения'), ('nz', 'Новая Зеландия'), ('zb', 'Зимбабве')], max_length=511, verbose_name='Локация'),
        ),
    ]
