# Generated by Django 5.0.6 on 2024-06-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('green', 'Зелёный'), ('blue', 'Синий'), ('yellow', 'Жёлтый'), ('black', 'Чёрный')], max_length=255, verbose_name='Цвет')),
                ('producer_country', models.CharField(max_length=255, verbose_name='Старана производитель')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FisingRod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('green', 'Зелёный'), ('blue', 'Синий'), ('yellow', 'Жёлтый'), ('black', 'Чёрный')], max_length=255, verbose_name='Цвет')),
                ('producer_country', models.CharField(max_length=255, verbose_name='Старана производитель')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('lenght', models.PositiveIntegerField(verbose_name='Длинна')),
                ('construction', models.CharField(max_length=255, verbose_name='Конструкция')),
                ('fish_type', models.CharField(max_length=255, verbose_name='Вид рыбы')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('green', 'Зелёный'), ('blue', 'Синий'), ('yellow', 'Жёлтый'), ('black', 'Чёрный')], max_length=255, verbose_name='Цвет')),
                ('producer_country', models.CharField(max_length=255, verbose_name='Старана производитель')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель оружия')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес в граммах')),
                ('calibr', models.CharField(max_length=255, verbose_name='Калибр')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
