# Generated by Django 5.0.6 on 2024-06-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rentplace_location'),
        ('products', '0005_rentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentorder',
            name='places',
        ),
        migrations.AddField(
            model_name='rentorder',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rentplace'),
        ),
    ]
