# Generated by Django 5.0.6 on 2024-06-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_rentorder_places_rentorder_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='rentorder',
            options={'verbose_name': 'Заказ оренды', 'verbose_name_plural': 'Заказы оренды'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
